server:
  port: 9200

eureka:
  client:
    serviceUrl:
      #设置服务注册中心的URL，本服务要向该服务注册中心注册自己
      defaultZone: http://127.0.0.1:1111/eureka
logging:
  level:
    root: info
spring:
  application:
    #设置服务名
    name: service-user
  #数据库连接信息
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/shop-user?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
 #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:java/com.ll/shop/user/dao/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.ll.shop.user.entity
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
